### ISSUE TITLE
When docker:release fails the exit code is 0

### ISSUE THREAD

**Issue by matthew-andrews** [heroku/heroku-docker#116]
It probably should be non zero.  E.g:-

```
mandrews@MATT ~/sandboxes/next-redirector (master) $ heroku docker:release --app ft-redirector-branch-50a6cd6
 !    Error: ENOENT: no such file or directory, open '/Users/mandrews/sandboxes/next-redirector/app.json'
mandrews@MATT ~/sandboxes/next-redirector (master) $ echo $?
0
```

Also, since when was `app.json` required?

**Comment by friism** [comment]
Hey Andrew, sorry this caught you unawares. We're rolling out a big update today, some details here: https://github.com/heroku/heroku-docker/issues/114

I sent out update to what I thought was current users last night. Will forward to you.
Michael

**Comment by hunterloftis** [comment]
I'm gonna re-open this @friism so we can ensure the exit code for failures is nonzero.

**Comment by matthew-andrews** [comment]
> last night

Take us more than a night to respond to this kind of change :disappointed:

**Comment by hunterloftis** [comment]
Sorry for the abrupt switch under your feet @matthew-andrews ... future changes likely won't be as massive, but do expect future changes as this is still in very beta status. It should take pretty minimal changes to update:

#### Create an `app.json` with at least an 'image', eg:

```js
{
  "image": "heroku/nodejs"
}
```

#### Ensure that you have a `Procfile`, eg:

```
web: node server.js
```

#### Ensure that you have Docker-Compose installed

```
$ docker-compose -v
```

#### Create a Dockerfile and a docker-compose.yml

```
$ heroku docker:init
```

#### Run the app locally

```
$ docker-compose up web
```

#### Release the app

```
$ heroku docker:release
```

**Comment by matthew-andrews** [comment]
I saw those docs…  The current problem I'm trying to diagnose is this error on Circle CI:-
```
heroku docker:release --app "ft-redirector-branch-b54f9ae"
Remote addons:  (0)
Local addons:  (0)
Missing addons:  (0)
Creating local slug...
 !    Error: spawn EACCES
```

**Comment by matthew-andrews** [comment]
Ok that's fixed, now I get:-

```
client and server don't have same version (client : 1.19, server: 1.18)
```
when running `docker-compose build web`

**Comment by hunterloftis** [comment]
It's awesome that you folks are building with docker all the way through circle to heroku.

Docker clients aren't backwards-compatible with old servers (https://github.com/docker/docker/issues/14077) so you'll want to either upgrade the server or downgrade the client to have them match.

**Comment by matthew-andrews** [comment]
This looks promising… http://stackoverflow.com/questions/31213195/running-docker-container-tests-on-circleci

**Comment by hunterloftis** [comment]
Once you get this sorted @matthew-andrews let us know if you'd be interested in authoring the Docker + CircleCI Heroku DevCenter article ;)

/cc @jonmountjoy

**Comment by matthew-andrews** [comment]
It's going to be a short blog post:-
> Does not work.  Use the Platform API instead

I can't figure out how to upgrade Docker on Circle CI so I'm giving up.

Unless…  Is there a way we can use the old docker-heroku plugin for the time being?

**Comment by hunterloftis** [comment]
does it make sense to just install client version 1.18?

To use an old version of the plugin, you can clone this repo and use `heroku plugins:link` (basically, the development workflow for a plugin). Keep in mind that the CLI auto-updates periodically so this may get sort of annoying.

**Comment by matthew-andrews** [comment]
Might seem like a stupid question but how would I  install client version 1.18?

**Comment by friism** [comment]
@matthew-andrews we don't actually ship the docker executable (we just shell out to it from the CLI plugin), so this is really strange.

**Comment by friism** [comment]
@matthew-andrews maybe you can grab the older compose version like this: https://docs.docker.com/compose/install/

**Comment by hunterloftis** [comment]
@matthew-andrews good question; you're seeing all of these errors on circleci, right, not locally? I assume the errors started right after you installed docker-compose on circleci?

**Comment by matthew-andrews** [comment]
oh right so it's the compose client that needs to be compatible with the docker server?  I'll definitely try installing an older client if that's the case.

**Comment by hunterloftis** [comment]
I *think* so - I've been looking for some sort of docker docs relating the tightly-coupled docker-client / docker-server / docker-compose versions, but no luck yet...

**Comment by matthew-andrews** [comment]
@hunterloftis you're right! docker-compose 1.3.3 did the trick

I've also managed to reduce the changes we need to make to the apps to this:-

**Create an `app.json` with the following contents:**
```json
{
  "mount_dir": "../src"
}
```

This is making use of some undocumented functionality I found in the code so in the long term I'll update our [Dockerfile](http://github.com/financial-times/n-dockerfile).  Once that's fixed I _think_ `{}` should be sufficient to make this work(!)

**Create a `docker-compose.yml` file with the following contents:**
```json
web:
  build: .
```

https://github.com/Financial-Times/next-redirector/pull/61/files

**Comment by hunterloftis** [comment]
Glad you sorted it out! `mount_dir` to '../src' was clever, as we essentially renamed 'src' to 'user' for 1.0 ('src' didn't make sense with Java).
