### ISSUE TITLE
MySQL (ClearDB) image support

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/heroku-docker#126]
Hi,

I've found that the cleardb addon [isn't supported](https://github.com/heroku/heroku-docker/blob/master/lib/addons.js) as docker image. Can this be added or simulated somehow?

**Comment by friism** [comment]
That'd be great! Do you want to take a stab at adding it? Details here:

 * https://github.com/heroku/heroku-docker#add-ons
 * https://devcenter.heroku.com/articles/docker#add-on-mapping
 * https://github.com/heroku/heroku-docker/blob/master/lib/addons.js

**Comment by boboldehampsink** [comment]
Sure! I'm just wondering if I can use a default `mysql` image or not

**Comment by friism** [comment]
Yes, I think that would be a great start

**Comment by boboldehampsink** [comment]
Ok, let the hacking begin :-)

**Comment by boboldehampsink** [comment]
Ok, I've encountered some problems where this implementation differs from the others. This image needs some env. variables of its own, and the current node script doesn't support that (yet). Working on it :-)

**Comment by friism** [comment]
Awesome, guessing the problem is that ROOT_PASSWORD is required: https://hub.docker.com/r/mysql/mysql-server/

**Comment by boboldehampsink** [comment]
Yes, here's more details about those variables: https://github.com/docker-library/docs/tree/master/mysql#environment-variables

The actual problem is that there's a `cleardb` section generated in the docker-compose.yml file, but the env variables are being set at the `web` and `shell` section. This means the `cleardb` image can't run on its own and therefore fails to attach. I should come up with a way in the node script to have addons have their own env. variables.

**Comment by boboldehampsink** [comment]
Submitted a few PR's to make this possible
