### ISSUE TITLE
Ruby version hard coded in Dockerfile?

### ISSUE THREAD

**Issue by BM5k** [heroku/heroku-docker#65]
After running `heroku docker:init`, when I run `heroku docker:start` I’m getting the following output

```
Your Ruby version is 2.2.1, but your Gemfile specified 2.2.2
Removing intermediate container f55bd50d8d85
 !    Error: Unable to create start image
```

Changing `ENV RUBY_ENGINE 2.2.1` to `ENV RUBY_ENGINE 2.2.2` in the generated Dockerfile seems to have fixed this.

**Comment by hunterloftis** [comment]
Glad you were to work around by updating your Dockerfile. The Ruby version should be detected:

- https://github.com/heroku/heroku-docker/blob/master/platforms/ruby/Dockerfile.t#L8

Perhaps the detect isn't always accurate? Pinging @friism

**Comment by hunterloftis** [comment]
Resolved by https://github.com/heroku/heroku-docker/pull/69
