### ISSUE TITLE
To docker-compose or not to docker-compose?

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-docker#82]
Docker-compose brings lots of existing, standard workflow for almost-free.

However, it doesn't have an API so we'll be shelling out to it. It also has lots of open issues / edge cases and isn't yet supported on Windows.

Does it make sense to implement a compose-based workflow, or should we use Docker's API to stand up, link, etc containers ourselves based on something like app.json?

**Comment by cyx** [comment]
I think if docker-compose isn't feature complete in the ways we need, might
be worth being involved with it?

**Comment by hunterloftis** [comment]
https://github.com/heroku/heroku-docker/tree/compose integrates docker-compose.
