### ISSUE TITLE
Decoupling platform implementations from the plugin

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-docker#83]
We definitely need to do this, but how?

Use the Docker registry? In this case, how can the platforms provide things like `detect`, `mountDir`, and templating? Other ideas?

**Comment by hunterloftis** [comment]
https://github.com/heroku/heroku-docker/tree/compose uses docker hub. Skips `detect` in favor of an explicit `image` key in app.json. Dumps volume mounting so no need for `mountDir`. No templating.

**Comment by cyx** [comment]
feels right
