### ISSUE TITLE
apt-get install?

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-docker#84]
This would be awesome, but is it possible when the only way of releasing a Docker image is to bundle `/app` up as a slug?

**Comment by cyx** [comment]
If we document something for the interim using ddollar's apt-get, maybe?

**Comment by friism** [comment]
I mean, it can be done but may not always work: https://gist.github.com/friism/4852b3becbfa13ad8c2e

**Comment by hunterloftis** [comment]
I feel like the amount of hackery necessary to get apt-get working defeats the original purpose of apt-get :/

**Comment by hunterloftis** [comment]
Ignored for https://github.com/heroku/heroku-docker/tree/compose

**Comment by kvarga** [comment]
@hunterloftis how does compose fix this?

**Comment by friism** [comment]
@kvarga it doesn't, I'm afraid. With the current Heroku container format, it's very hard for us to support running apt-get installs.

**Comment by kvarga** [comment]
Would it be similar to the way its handled with buildpacks where you have to vendor in the code and update a bunch of ENV? Seems like everything is limited to changes in /app to get deployed.

**Comment by friism** [comment]
@kvarga exactly, there's some code here: https://gist.github.com/friism/4852b3becbfa13ad8c2e
