### ISSUE TITLE
Composability & custom Dockerfiles

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-docker#86]
One of the major flaws in buildpacks is that they're tricky to compose and customize. Docker offers, basically, the other end of the spectrum: you can add whatever you want.

It would currently be a pain to, for example, use Node + Python. Just like buildpacks, we have a Node platform and a Python platform, and no first-class mechanism for using them together.

Can anyone think of a better way?

**Comment by friism** [comment]
I like @jesperfj idea of publishing docker images instead of writing out big Dockerfiles in `init` that will go stale as we make improvements

**Comment by hunterloftis** [comment]
I agree; one of our benefits is making upstream patches for you.

The question to answer here is: do we really need templating? That was a big factor into my decision to write Dockerfile templates into platforms; we talked a lot initially about how Dockerfiles are limiting and how we would need to templatize them.

I'm not sure that is true, but we should ensure that we'll be able to do everything we want with published docker images.

**Comment by tt** [comment]
I propose that we keep the templates for now, but that we also begin to adopt Docker images where it makes sense.

For instance, the Go language is has very few versions and little variability. I definitely think we should publish a `heroku/go` image for each version. This might be the same for Node.js and even for the base Ruby versions.

Each language can then still have a template which in some cases (i.e. Go and Node.js) will select the appropriate base image and in other cases (i.e. Ruby) do that and also apply additional instructions.

**Comment by hunterloftis** [comment]
@tt +1, I can do most of what node does with version tags, but I doubt that's true for ruby.

**Comment by hunterloftis** [comment]
The tricky bit is - this leaves the platforms coupled to the plugin :(

Let's come up with some ideas on alternatives to that, specifically.

**Comment by hunterloftis** [comment]
Right now each platform exposes (or will expose):

- `name`, the platform's name
- `detect(dir)`, to detect the platform on `init`
- `mountDir()`, the directory into which to mount the local app volume

Additionally, the platforms object provides a list of platforms (the detect order).

How can we provide this data externally (removing everything in `/platforms`)? Ideally, via some data attached to the Dockerfile / image itself on the registry.

**Comment by hunterloftis** [comment]
https://github.com/heroku/heroku-docker/tree/compose uses docker hub images (https://registry.hub.docker.com/u/hunterloftis/node/). The local Dockerfile begins with just `FROM owner/image[:tag]` and can be extended by adding more Dockerfile commands below.

For instance, you could add dependencies like imagemagick, compass, etc via this mechanism. Upstream changes to the image can still be incorporated since we're using `FROM` instead of templates this time around.

**Comment by friism** [comment]
This feels right.
