### ISSUE TITLE
ENV NODE_ENGINE 0.10.38 <- How to I switch this to io.js latest?

### ISSUE THREAD

**Issue by dstroot** [heroku/heroku-docker#87]
Can't figure it out.  Help!

**Comment by hunterloftis** [comment]
Hi @dstroot - the plugin currently only supports the node project; PRs for iojs support welcome!

- https://github.com/heroku/heroku-docker/blob/master/platforms/node/Dockerfile.t#L13

(however, since they're merging, any such change will likely be short-lived)

**Comment by dstroot** [comment]
Ok thanks. Glad they are merging back.  ;)
