### ISSUE TITLE
Plugin won't install

### ISSUE THREAD

**Issue by werkshy** [heroku/heroku-docker#89]
Ubuntu 14.04

    heroku-toolbelt/3.37.1 (x86_64-linux) ruby/2.0.0
    heroku-cli/4.19.23-802a7d4 (amd64-linux) go1.4.2
    You have no installed plugins.

I do not have node or io.js installed on my system.

<pre>
oneill@d1:~ $ heroku plugins:install docker
Installing Heroku Toolbelt v4... done
Installing plugin docker...  ▸    sh: 1: node: not found
 ▸    npm ERR! Linux 3.13.0-48-generic
 ▸    npm ERR! argv "/home/oneill/.heroku/iojs-v2.0.2-linux-x64/bin/iojs" "/home/oneill/.heroku/iojs-v2.0.2-linux-x64/lib/node_modules/npm/cli.js" "install" "docker"
 ▸    npm ERR! node v2.0.2
 ▸    npm ERR! npm  v2.9.0
 ▸    npm ERR! file sh
 ▸    npm ERR! code ELIFECYCLE
 ▸    npm ERR! errno ENOENT
 ▸    npm ERR! syscall spawn
 ▸    
 ▸    npm ERR! typechecker@2.0.8 preinstall: `node ./cyclic.js`
 ▸    npm ERR! spawn ENOENT
 ▸    npm ERR! 
 ▸    npm ERR! Failed at the typechecker@2.0.8 preinstall script 'node ./cyclic.js'.
 ▸    npm ERR! This is most likely a problem with the typechecker package,
 ▸    npm ERR! not with npm itself.
 ▸    npm ERR! Tell the author that this fails on your system:
 ▸    npm ERR!     node ./cyclic.js
 ▸    npm ERR! You can get their info via:
 ▸    npm ERR!     npm owner ls typechecker
 ▸    npm ERR! There is likely additional logging output above.
 ▸    
 ▸    npm ERR! Please include the following file with any support request:
 ▸    npm ERR!     /home/oneill/.heroku/npm-debug.log
</pre>

I tried adding the iojs bin dir to my PATH, but then I get

<pre>
oneill@d1:~ $ pathadd /home/oneill/.heroku/iojs-v2.0.2-linux-x64/bin
oneill@d1:~ $ heroku plugins:install docker
Installing plugin docker... 
This does not appear to be a Heroku plugin, uninstalling... done
</pre>

**Comment by hunterloftis** [comment]
Hmm, @dickeyxxx any ideas?

**Comment by dickeyxxx** [comment]
very strange. Maybe try deleting `~/.heroku/iojs-v2.0.2-linux-x64`? I fixed some stuff around the updater with that. Not sure if it's related though.

**Comment by dickeyxxx** [comment]
also, do you have anything in your `~/.npmrc` that might be causing this? I need to override those options, but it's a manual process.

**Comment by werkshy** [comment]
No ~/.npmrc

I tried deleting the whole iojs directory too. No dice.

**Comment by dickeyxxx** [comment]
@werkshy can you send me that log? /home/oneill/.heroku/npm-debug.log I'm not sure where cyclic.js and typechecker are even coming from. Also, can you install a different plugin? Like `heroku-local`?

**Comment by werkshy** [comment]
heroku-local installs fine.

Here's the debug log.
https://gist.github.com/werkshy/f5349e8f084bf145b7ab

**Comment by dickeyxxx** [comment]
OH! I figured it out. You're trying to install the `docker` package, the package you meant to install is `heroku-docker`. `heroku plugins:install heroku-docker`

cc @hunterloftis

**Comment by werkshy** [comment]
Oh jeebus. Sorry! Makes sense now.

Thanks for taking the time. At least when some other idiot comes asking you'll know what they did wrong!

**Comment by dickeyxxx** [comment]
yeah sorry it took so long to notice!
