### ISSUE TITLE
Dockerfile.t proposed improvements

### ISSUE THREAD

**Issue by nzoschke** [heroku/heroku-docker#9]
Dockerfile best practices suggests to minimize layers by chaining more commands together in a RUN.

https://docs.docker.com/articles/dockerfile_best-practices/

Here are a couple suggestions for doing this better in the node Dockerfile.t...

```
RUN mkdir -p app/{heroku,src,.profile.d}
```
```
RUN curl -s http://s3pository.heroku.com/node/v0.10.30/node-v0.10.30-linux-x64.tar.gz \
  | tar vxz -C /app/heroku --strip-components=2 node-v0.10.30-linux-x64/bin/node
```

Probably could unify the nodejs.sh setup too.

Just a suggestion

**Comment by iatsiuk** [comment]
@friism you can use `bash -c "mkdir -p dir/{one,two}"` (if bash is available).

**Comment by friism** [comment]
Closing this issue, see Dockerfile best practices for more ideas: https://docs.docker.com/articles/dockerfile_best-practices/
